networks:
    dcp:
        name: dcp
        external: true

services:
    leetcode-scraper:
        build: .
        environment:
            # LeetCode
            - CSRF_TOKEN=${CSRF_TOKEN}
            - LEETCODE_SESSION=${LEETCODE_SESSION}

            # PostgreSQL
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_HOST=${POSTGRES_HOST}
            - POSTGRES_PORT=${POSTGRES_PORT}
        volumes:
            - ./scripts/entrypoint.sh:/usr/src/app/entrypoint.sh
        entrypoint: ["/usr/src/app/entrypoint.sh"]
        networks:
            - dcp
